# Generated by Django 3.1.1 on 2020-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200927_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_picture',
            field=models.ImageField(blank=True, upload_to='images/pro_pic/'),
        ),
    ]
