# Generated by Django 3.1.1 on 2020-10-03 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
