# Generated by Django 3.1.1 on 2020-10-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20201003_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
