# Generated by Django 3.1.1 on 2020-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='time',
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
