# Generated by Django 3.1.1 on 2020-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20200921_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='com_id',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exh_id',
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
