# Generated by Django 3.1.1 on 2020-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20200927_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='com_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='competition',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exh_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
