# Generated by Django 3.1.1 on 2020-10-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0012_delete_arrange'),
        ('Event', '0005_auto_20200927_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exhibition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='com_id',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='time',
        ),
    ]
