# Generated by Django 3.1.1 on 2020-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20201002_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
