# Generated by Django 3.1.1 on 2020-10-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0007_auto_20201002_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('medium', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/image/')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.competition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
