# Generated by Django 3.1.1 on 2020-10-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitcompetition',
            name='reviews',
            field=models.ManyToManyField(to='Event.Review'),
        ),
    ]
