# Generated by Django 3.1.1 on 2020-09-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('medium', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
