# Generated by Django 3.1.1 on 2020-09-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artworks',
            new_name='Artwork',
        ),
    ]
