# Generated by Django 3.1.1 on 2020-09-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
        ('Artwork', '0002_auto_20200919_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artwork.artwork')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.competition')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.exhibition')),
            ],
            options={
                'unique_together': {('a_id', 'e_id', 'c_id')},
            },
        ),
    ]
