# Generated by Django 3.1.1 on 2020-09-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20200921_1459'),
        ('Artwork', '0004_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.user'),
        ),
        migrations.DeleteModel(
            name='Create',
        ),
    ]
