# Generated by Django 3.1.1 on 2020-09-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0005_auto_20200921_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='email',
            new_name='user',
        ),
    ]
