# Generated by Django 3.1.1 on 2020-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0006_auto_20200927_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art',
            field=models.ImageField(blank=True, upload_to='images/art/'),
        ),
    ]
