# Generated by Django 3.1.1 on 2020-09-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20200921_1505'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Artwork', '0007_artwork_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrange',
            old_name='a_id',
            new_name='artwork',
        ),
        migrations.AddField(
            model_name='arrange',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Event.competition'),
        ),
        migrations.AddField(
            model_name='arrange',
            name='exhibition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Event.exhibition'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='art_description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='art',
            field=models.ImageField(upload_to='images/art/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='arrange',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='arrange',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='arrange',
            name='e_id',
        ),
    ]
