# Generated by Django 3.1.1 on 2020-10-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0011_auto_20201001_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrange',
        ),
    ]
