# Generated by Django 3.1.1 on 2020-10-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0012_delete_arrange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
    ]
