# Generated by Django 3.1.1 on 2020-10-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0013_remove_artwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
